language: node_js
node_js:
  - '8'
script:
  - 'npm test'
  - 'npm run lint'
notifications:
  webhooks:
    urls:
      - 'https://www.travisbuddy.com/?insertMode=update'
    on_success: always
    on_failure: always
    on_start: never
    on_cancel: never
    on_error: never
travisBuddy: 
  templates:
    success: default
    failure: default
  insertMode: update